package dev.SeanZhang.gameOfLife.game;

import com.sun.glass.events.KeyEvent;
import dev.SeanZhang.gameOfLife.game.GameEngine;
import dev.SeanZhang.utils.Utils;
import java.awt.Color;

import java.awt.GridLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author seanz
 */
public class GameDisplay extends javax.swing.JFrame {

    ImageIcon logo;

    public GameDisplay() {
        logo = new ImageIcon(getClass().getResource("/res/logo/GameOfLife.png"));
        initComponents();
        setIconImage(logo.getImage());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        startStopButton = new javax.swing.JButton();
        speedSlider = new javax.swing.JSlider();
        speedLabel = new javax.swing.JLabel();
        presetCombo = new javax.swing.JComboBox<>();
        clearButton = new javax.swing.JButton();
        widthGBoard = new javax.swing.JTextField();
        gb = new dev.SeanZhang.gameOfLife.game.GameBoard();
        widthButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        toggleCol = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Game Of Life");
        setPreferredSize(new java.awt.Dimension(820, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(820, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        startStopButton.setText("Start");
        startStopButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                startStopButtonMousePressed(evt);
            }
        });
        getContentPane().add(startStopButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, -1, -1));

        speedSlider.setMaximum(5000);
        speedSlider.setMinimum(1);
        speedSlider.setValue(25);
        speedSlider.setInverted(true);
        speedSlider.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                speedSliderStateChanged(evt);
            }
        });
        getContentPane().add(speedSlider, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, 147, -1));

        speedLabel.setText("Speed");
        getContentPane().add(speedLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 410, -1, -1));

        presetCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Custom", "Glider Gun", "Pulsar" }));
        presetCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presetComboActionPerformed(evt);
            }
        });
        getContentPane().add(presetCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 181, -1));

        clearButton.setText("Clear Stuf");
        clearButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                clearButtonMousePressed(evt);
            }
        });
        getContentPane().add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        widthGBoard.setForeground(new java.awt.Color(204, 204, 204));
        widthGBoard.setText("Enter Width");
        widthGBoard.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                widthGBoardMouseClicked(evt);
            }
        });
        widthGBoard.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                widthGBoardKeyPressed(evt);
            }
        });
        getContentPane().add(widthGBoard, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 95, -1));

        gb.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gb.setPreferredSize(new java.awt.Dimension(600, 600));

        javax.swing.GroupLayout gbLayout = new javax.swing.GroupLayout(gb);
        gb.setLayout(gbLayout);
        gbLayout.setHorizontalGroup(
            gbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        gbLayout.setVerticalGroup(
            gbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );

        getContentPane().add(gb, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        widthButton.setText("Enter");
        widthButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                widthButtonMouseClicked(evt);
            }
        });
        getContentPane().add(widthButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 360, -1, -1));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/res/logo/GamOfLife_Small.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 0, 220, 200));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Game of Life");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, 220, 90));

        toggleCol.setText("Toggle Colors");
        toggleCol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                toggleColMousePressed(evt);
            }
        });
        getContentPane().add(toggleCol, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    int hasStarted = -1;
    private void startStopButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startStopButtonMousePressed
        hasStarted *= -1;
        gb.toggleTick();
        if (gb.returnTick()) {
            startStopButton.setText("Stop");
        } else {
            startStopButton.setText("Start");
        }
    }//GEN-LAST:event_startStopButtonMousePressed

    private void clearButtonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearButtonMousePressed
        gb.getGameEngine().clearScreen();
        if (gb.returnTick()) {
            gb.toggleTick();
            startStopButton.setText("Start");
        }
    }//GEN-LAST:event_clearButtonMousePressed

    private void widthGBoardKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_widthGBoardKeyPressed
        int k = KeyEvent.VK_ENTER;
        if (evt.getKeyCode() == k) {
            gb.setGWidth(Integer.parseInt(widthGBoard.getText()));
            widthGBoard.setForeground(new Color(204, 204, 204));
            widthGBoard.setText("Enter Width");
        }
    }//GEN-LAST:event_widthGBoardKeyPressed

    private void speedSliderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_speedSliderStateChanged
        gb.stopTimer();
        gb.setTimer((int) speedSlider.getValue());
    }//GEN-LAST:event_speedSliderStateChanged

    private void presetComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presetComboActionPerformed
        int chosenPreset = presetCombo.getSelectedIndex();

        switch (chosenPreset) {
            case 0:

                break;

            case 1:
                genMap("src/res/presets/preset1.txt");
                break;

            case 2:
                genMap("src/res/presets/preset2.txt");
                break;
        }
    }//GEN-LAST:event_presetComboActionPerformed

    private void widthGBoardMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_widthGBoardMouseClicked
        widthGBoard.setForeground(Color.BLACK);
        widthGBoard.setText("");
    }//GEN-LAST:event_widthGBoardMouseClicked

    private void widthButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_widthButtonMouseClicked
        gb.setGWidth(Integer.parseInt(widthGBoard.getText()));
        widthGBoard.setForeground(new Color(204, 204, 204));
        widthGBoard.setText("Enter Width");
    }//GEN-LAST:event_widthButtonMouseClicked
    
    private void toggleColMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toggleColMousePressed
        gb.toggleC();
    }//GEN-LAST:event_toggleColMousePressed

    public void genMap(String path) {
        String file = Utils.loadFileAsString(path);
        String[] brokenFile = file.split("\\s+");
        int w = Utils.parseInt(brokenFile[0]);
        if (gb.width < w) {
            gb.setGWidth(w);
        }
        gb.getGameEngine().clearScreen();
        for (int i = 1; i < brokenFile.length; i++) {
            if (Utils.parseInt(brokenFile[i]) > 0) {
                gb.getGameEngine().toggleValue((i - 1) % w, ((i - 1) / w));
            }
        }
        gb.setTimer(-1);
    }

    /**
     * @param args the command line arguments
     *
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameDisplay.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameDisplay().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private dev.SeanZhang.gameOfLife.game.GameBoard gb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> presetCombo;
    private javax.swing.JLabel speedLabel;
    private javax.swing.JSlider speedSlider;
    private javax.swing.JButton startStopButton;
    private javax.swing.JButton toggleCol;
    private javax.swing.JButton widthButton;
    private javax.swing.JTextField widthGBoard;
    // End of variables declaration//GEN-END:variables

}
